<a href="https://colab.research.google.com/github/christinapenheiro/Student-Performance-Analyzer-Using-Numpy/blob/main/main.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
students_dataset = np.array([[85,90,78,88],[72,65,80,70],[95,92,94,96],[60,75,68,72],[78,82,85,80]])
student_names = np.array(["Alice","Bob","Charlie","Diana","Ethan"])
students_sub = np.array(["Math","Python","Numpy","Stats"])

##Feature 1 — Create and inspect the dataset

In [3]:
students_dim = np.ndim(students_dataset)
print("students dimension: ",students_dim)
students_shape = np.shape(students_dataset)
print("students shape: ",students_shape)
students_size = np.size(students_dataset)
print("students size:",students_size)
data_type = students_dataset.dtype
print("students data type",data_type)


##Access one student's marks and one subject's marks using indexing and slicing.

student_name_charlie_position = np.where(student_names == "Charlie")
sub_math = np.where(students_sub=="Math")
student_charlie_math_number = students_dataset[student_name_charlie_position[0][0],sub_math[0][0]]
charlie_numbers = students_dataset[student_name_charlie_position[0][0]]
print(f"Charlie's position {student_name_charlie_position[0][0]}: All marks {charlie_numbers}")
print(f"Math position {sub_math[0][0]}: Number {student_charlie_math_number}")

sub_numpy = np.where(students_sub=="Numpy")
numpy_marks = students_dataset[:,sub_numpy[0][0]]
print("Numpy marks: ",numpy_marks)

students dimension:  2
students shape:  (5, 4)
students size: 20
students data type int64
Charlie's position 2: All marks [95 92 94 96]
Math position 0: Number 95
Numpy marks:  [78 80 94 68 85]

##Feature 2 — Calculate student statistics

In [4]:
#Calculate each student's total marks.
each_students_total_mark = students_dataset.sum(axis=1)
print(each_students_total_mark)

each_students_average = students_dataset.mean(axis=1)
# each_students_average

#highest and lowest mark in the entire dataset
highest_mark = students_dataset.max()
highest_mark

lowest_mark = students_dataset.min()
lowest_mark

#the average mark for each subject
each_sub_avg_mark = students_dataset.mean(axis=0)
each_sub_avg_mark

[341 287 377 275 325]

array([78. , 80.8, 81. , 81.2])

In [34]:
#new dataset table using pandas
new_students_data = pd.DataFrame(students_dataset,index=student_names,columns=students_sub)
new_students_data["Total mark"] = each_students_total_mark
new_students_data["Average"] = each_students_average
new_students_data

         Math  Python  Numpy  Stats  Total mark  Average
Alice      85      90     78     88         341    85.25
Bob        72      65     80     70         287    71.75
Charlie    95      92     94     96         377    94.25
Diana      60      75     68     72         275    68.75
Ethan      78      82     85     80         325    81.25

##Feature 3 — Identify passing and failing students

In [69]:
mask = students_dataset < 70
# result = np.where(students_dataset < 70,False,True)
result = students_dataset >= 70

#Subject wise passed students count
sub_wise_passed_result = result.sum(axis=0)


#Subject wise failed students count
row = students_dataset.shape[0]
sub_wise_failed_result = row - sub_wise_passed_result

In [81]:
#students who passed all four subjects

passed_students = new_students_data.loc[(new_students_data >= 70).all(axis=1)]
arr = np.array(passed_students.index)
print("All subject passed students are",arr)

All subject passed students are ['Alice' 'Charlie' 'Ethan']

In [80]:
#subjects whose average is below 75
sub_avg_below75 = students_sub[students_dataset.mean(axis=0) < 75]
sub_avg_below75

array([], dtype='<U6')

##Feature 4 — Build a ranking system

In [116]:
#Find the student with the highest average.
highest_avg_student = new_students_data[new_students_data["Average"] == new_students_data["Average"].max()].index
print(f'Highest average student name {highest_avg_student[0]}')

Highest average student name Charlie

In [117]:
#Find the student with the lowest average.

lowest_avg_student = new_students_data[new_students_data["Average"] == new_students_data["Average"].min()].index
print(f'Lowest average student name {lowest_avg_student[0]}')

Lowest average student name Diana

In [118]:
#Rank students from highest to lowest average.
highest_to_lowest_avg = new_students_data["Average"].sort_values(ascending=False)
print(np.array(highest_to_lowest_avg.index))

['Charlie' 'Alice' 'Ethan' 'Bob' 'Diana']

In [129]:
#Display each student's name alongside their average.
#As Pandas automatically displays the index (student names) alongside the average values.
# used reset_index() with .rename() to converts the student names from the index into a regular column
#and renamed it to names


new_table = highest_to_lowest_avg.reset_index().rename(columns={"index":"Name"})
new_table

      Name  Average
0  Charlie    94.25
1    Alice    85.25
2    Ethan    81.25
3      Bob    71.75
4    Diana    68.75

##Feature 5 — Add a performance report